const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const source=fs.readFileSync(require('node:path').join(__dirname,'../agents/meshcore.js'),'utf8');
const helper=source.slice(source.indexOf('function closeFileDownload('),source.indexOf('function onTunnelClosed('));
const download=source.slice(source.indexOf("                case 'download':"),source.indexOf("                case 'upload':",source.indexOf("                case 'download':")));
function fixture(){let id=0;const open=new Set(),closed=[],sent=[];const io={openSync(){open.add(id);return id++;},closeSync(fd){assert.ok(open.delete(fd),'descriptor closed once');closed.push(fd);},readSync(fd,buf){assert.ok(open.has(fd));return 16380;}};const context={fs:io,Buffer,MeshServerLogEx(){},process:{platform:'win32'}};vm.runInNewContext(helper+'\nfunction run(cmd){switch(cmd.action){'+download+'}}\nthis.run=run;',context);const socket={httprequest:{},write(value){sent.push(value);}};return {io,context,socket,open,closed,sent,run:cmd=>context.run.call(socket,{action:'download',id:'1',...cmd})};}
test('stop releases descriptor zero exactly once and ignores mismatched IDs',()=>{const f=fixture();f.run({sub:'start',path:'x'});f.run({sub:'stop',id:'other'});assert.equal(f.open.size,1);f.run({sub:'stop'});f.run({sub:'stop'});assert.deepEqual(f.closed,[0]);});
test('replacement start and invalid start release prior descriptor',()=>{const f=fixture();f.run({sub:'start',path:'x'});f.run({sub:'start',path:'y',id:'2'});assert.deepEqual(f.closed,[0]);f.run({sub:'start',path:null});assert.deepEqual(f.closed,[0,1]);});
test('EOF and read/write errors release descriptor',()=>{for(const mode of ['eof','read','write','startwrite']){const f=fixture();if(mode==='startwrite')f.socket.write=()=>{throw Error('write');};f.run({sub:'start',path:'x'});if(mode==='eof')f.io.readSync=()=>0;if(mode==='read')f.io.readSync=()=>{throw Error('read');};if(mode==='write')f.socket.write=()=>{throw Error('write');};f.run({sub:'startack',ack:1});assert.equal(f.open.size,0,mode);assert.deepEqual(f.closed,[0],mode);}});
test('failed open cancels without closing an unowned descriptor',()=>{const f=fixture();f.io.openSync=()=>{throw Error('denied');};f.run({sub:'start',path:'x'});assert.equal(f.socket.filedownload,undefined);assert.equal(f.closed.length,0);assert.equal(f.sent.at(-1).sub,'cancel');});
test('file end handler releases an interrupted transfer and is idempotent',()=>{const f=fixture();const a=source.indexOf('function files_tunnel_endhandler()'),b=source.indexOf('function registry_consent_ok',a);vm.runInNewContext(source.slice(a,b),f.context);f.run({sub:'start',path:'x'});f.context.files_tunnel_endhandler.call(f.socket);f.context.files_tunnel_endhandler.call(f.socket);assert.deepEqual(f.closed,[0]);});
test('tunnel close releases file before early return, including WebRTC channel',()=>{const f=fixture();const a=source.indexOf('function onTunnelClosed()'),b=source.indexOf('function onTunnelSendOk',a);Object.assign(f.context,{tunnels:{}});vm.runInNewContext(source.slice(a,b),f.context);f.run({sub:'start',path:'x'});const channel={filedownload:{f:f.io.openSync('rtc')}};Object.assign(f.socket,{tunnel:{},webrtc:{rtcchannel:channel}});f.context.onTunnelClosed.call(f.socket);assert.equal(f.open.size,0);assert.deepEqual(f.closed,[0,1]);});
